#!/usr/bin/env python
import os
import sys
import fileinput

class GentooOperations:
    """
    Performs various distro operations.
    """
    
    def installBasicDeps(self):
        os.system("emerge dev-vcs/git")

    def update(self):
        os.system("emerge --sync")
        os.system("layman -S")
        os.system("emerge --changed-use --deep world")
        os.system("emerge --update --deep --with-bdeps=y --ask @world")
        os.system("emerge @preserved-rebuild")

    def config(self, config):
        configVars = {
            'CHOST': 'x86_64-pc-linux-gnu',
            'CFLAGS': '-O2 -pipe',

            'USE': 'php apache2 systemd -openrc ruby_targets_ruby19 iptables mariadb',
            'RUBY_TARGETS': 'ruby19',
            'PHP_TARGETS': 'php5-6',


            'GENTOO_MIRRORS': 'ftp://ftp.ussg.iu.edu/pub/linux/gentoo http://ftp.ucsb.edu/pub/mirrors/linux/gentoo/',
            'SYNC': 'rsync://rsync25.us.gentoo.org/gentoo-portage',
            'ACCEPT_KEYWORDS': 'amd64',
            'CXXFLAGS': '${CFLAGS}',
            'PORTDIR': '/usr/portage',
            'DISTDIR': '${PORTDIR}/distfiles',
            'PKGDIR': '${PORTDIR}/packages'
        }

        configVars['CFLAGS'] = "-O2 -pipe"
        if config['config_settings']['native_compile']:
            configVars['CFLAGS'] += " -march=native"

        configVars['EMERGE_DEFAULT_OPS'] = "--jobs=" + str(config['config_settings']['num_cpus']) + " --load-average=" + str(config['config_settings']['num_cpus'])
        configVars['MAKEOPS'] = "-j" + str(config['config_settings']['num_cpus'])

        f = open('/etc/portage/make.conf.test', 'w')

        f.write("# THIS FILE WAS AUTOMATICALLY GENERATED BY PORT\n")
        f.write("# MODIFICATIONS WILL BE OVERRIDDEN\n")
        f.write("\n")

        for varName, varValue in configVars.items():
            f.write(varName)
            f.write("=\"")
            f.write(varValue)
            f.write("\"\n")
        f.write("\nsource /var/lib/layman/make.conf\n")
